version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: moviesDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  movie-task:

    build:
      context: .
      dockerfile: Dockerfile
    image: movietask
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/moviesDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    command: [ "java", "-jar", "app.jar" ]
